### ISSUE TITLE
MEDIA_BUS_FMT_Y10_1X10 support

### ISSUE THREAD

**Issue by martin-jansen** [aodzip/sun6i-mipi-csi#2]
I am trying to connect an OV7251 to my S3 board. The OV7251 uses MEDIA_BUS_FMT_Y10_1X10 and because there is no support in the mipi csi driver I have tried to add this.
[mipi_csi2_y10.zip](https://github.com/aodzip/sun6i-mipi-csi/files/5439501/mipi_csi2_y10.zip)

The communication with the camera module is working. Only the output is what I am expecting to receive. I think I have added the Y10 correct but obviously I have made an error along the way. If you have some time to look at my patch I would really appreciate it.

**Comment by martin-jansen** [comment]
The patch is working I made a mistake in the device tree.

**Comment by alenwp** [comment]
> I am trying to connect an OV7251 to my S3 board. The OV7251 uses MEDIA_BUS_FMT_Y10_1X10 and because there is no support in the mipi csi driver I have tried to add this. [mipi_csi2_y10.zip](https://github.com/aodzip/sun6i-mipi-csi/files/5439501/mipi_csi2_y10.zip)
> 
> The communication with the camera module is working. Only the output is what I am expecting to receive. I think I have added the Y10 correct but obviously I have made an error along the way. If you have some time to look at my patch I would really appreciate it.

hi martin, i use your patch, but i cannot get the Y10 picture（i can get yuyv picture）， and got the error `The pixelformat 'Y10' is invalid` , the following is my cmd. do you know how to solve this problem? or how to get the right picture ?  Look forward to your reply.
`# v4l2-ctl --set-fmt-video=width=640,height=480,pixelformat=Y10 --stream-mmap --stream-count=1 --stream-to=out.raw`

**Comment by martin-jansen** [comment]
You will need a little bit more code to make the Y10 work. Can you try the attached patch as well.
 ​​

**Comment by alenwp** [comment]
> 

Thanks for your reply.  I try the attached patch you gived well, but i cannot get the Y10 picture（i can get yuyv picture）， and got the error `The pixelformat 'Y10' is invalid`.

**Comment by alenwp** [comment]
> > I am trying to connect an OV7251 to my S3 board. The OV7251 uses MEDIA_BUS_FMT_Y10_1X10 and because there is no support in the mipi csi driver I have tried to add this. [mipi_csi2_y10.zip](https://github.com/aodzip/sun6i-mipi-csi/files/5439501/mipi_csi2_y10.zip)
> > The communication with the camera module is working. Only the output is what I am expecting to receive. I think I have added the Y10 correct but obviously I have made an error along the way. If you have some time to look at my patch I would really appreciate it.
> 
> hi martin, i use your patch, but i cannot get the Y10 picture（i can get yuyv picture）， and got the error `The pixelformat 'Y10' is invalid` , the following is my cmd. do you know how to solve this problem? or how to get the right picture ? Look forward to your reply. `# v4l2-ctl --set-fmt-video=width=640,height=480,pixelformat=Y10 --stream-mmap --stream-count=1 --stream-to=out.raw`

i use the wrong cmd. Thank Martin for his help. the right cmd is  
`# v4l2-ctl --set-fmt-video=width=640,height=480,pixelformat='Y10 ' --stream-mmap --stream-count=1 --stream-to=out.raw`
